type:
  {{cookiecutter.entityType}}

subType:
  WEB_APP

title:
  {{cookiecutter.entityTitle}}

description:
  {{cookiecutter.entityDescription}}

relatedSystem:
  {{cookiecutter.entityRelatedSystem}}

jenkins:
  job:
    <JENKINS_SERVICE_NAME>
